#!/bin/sh

# A dwm_bar function to show Bluetooth connection status
# Dependencies: bluetoothctl

dwm_bluetooth () {
    # Check if Bluetooth is powered on
    BT_POWER=$(bluetoothctl show | grep "Powered: yes")

    if [ -z "$BT_POWER" ]; then
        # Bluetooth is off
        printf "󰂲 Bluetooth Off"
    else
        # Check if any Bluetooth device is connected
        BT_STATUS=$(bluetoothctl devices Connected | grep "Device")

        if [ -n "$BT_STATUS" ]; then
            printf "󰂱"  # Icon for connected
        else
            printf ""  # Icon for disconnected
        fi
    fi
    printf "%s\n" "$SEP2"
}

dwm_bluetooth

